# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/naumen
    username: postgres
    password: 1412
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    web:
      pageable:
        default-page-size: 5
  web:
    resources:
      add-mappings: true
  h2:
    console:
      enabled: true

# VARIABLES
api:
  agify:
    url: https://api.agify.io?name=

person:
  reader:
    file:
      name: info.txt
      path: src/main/resources/
  count:
    default-value: 0
    start-value: 1
  age:
    default-value: 1000
    not-found-value: 0

# PORT
server:
  port: 8080