# H2 DB
spring:
  datasource:
    hikari:
      username: sa
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      password:
  data:
    web:
      pageable:
        default-page-size: 5
  web:
    resources:
      add-mappings: true
  h2:
    console:
      enabled: true

# VARIABLES
api:
  agify:
    url: https://api.agify.io?name=

person:
  reader:
    file:
      name: info.txt
      path: src/main/resources/
  count:
    default-value: 0
    start-value: 1
  age:
    default-value: 1000
    not-found-value: 0

# PORT
server:
  port: 8080
